services: 
  client:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./web:/usr/share/nginx/html
# # # # # Backend Service for Clients and Devices in Nodejs/
  backend:
       
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    hostname: backend
    ports:
      - "3002:3002" 
    restart: on-failure
    networks:
      - main-network   

 
# Networks between internal containers
networks:
  main-network:
    name: main-network
        